@startuml
'https://SubscriptionServicetuml.com/sequence-diagram



title Top 5 Readers

actor Librarian

participant ":LendingController" as Ctrl
participant ":LendingService" as Srv
participant ":LendingRepository" as Repo

Librarian -> Ctrl: Request top 5 readers (GET /top5readers)
Ctrl -> Srv: Find top readers
Srv -> Repo: Get all lendings
Repo --> Srv: List of lendings
Srv -> Srv: Calculate top 5 readers
Srv --> Ctrl: List of top 5 readers

Ctrl --> Librarian: Response with top 5 readers

@enduml