@startuml
'https://plantuml.com/sequence-diagram

title System Sequence Diagram US011 egister as a reader

autoactivate on
autonumber

actor " Anonymous" as Administrator
participant ":System" as System

activate Administrator

Administrator -> System:  Request to register as a reader
System --> Administrator: requests data (name, email, date of birth, phone number, GDPR  consent)

Administrator -> System: types requested data
System --> Administrator: shows all data and requests confirmation

Administrator -> System: confirms the data
System --> Administrator: informs operation success
@enduml